annotations:
  artifacthub.io/changes: |
    - description: Support labels specific to the database migration objects and pods
      kind: added
      links:
      - name: '#37490'
        url: https://github.com/apache/airflow/pull/37490

    - description: Flower K8s Probe config
      kind: changed
      links:
      - name: '#37528'
        url: https://github.com/apache/airflow/pull/37528

    - description: Remove duplicate ports key in webserver service
      kind: fixed
      links:
      - name: '#37356'
        url: https://github.com/apache/airflow/pull/37356

    - description: Add ``AIRFLOW_HOME`` env var to log groomer sidecar
      kind: fixed
      links:
      - name: '#37588'
        url: https://github.com/apache/airflow/pull/37588

    - description: Skip ``.`` path when preparing reproducible packages
      kind: fixed
      links:
      - name: '#37402'
        url: https://github.com/apache/airflow/pull/37402

    - description: 'Misc: Default airflow version to 2.8.2'
      kind: changed
      links:
      - name: '#37704'
        url: https://github.com/apache/airflow/pull/37704
  artifacthub.io/links: |
    - name: Documentation
      url: https://airflow.apache.org/docs/helm-chart/1.13.0/
  artifacthub.io/screenshots: |
    - title: DAGs View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/dags.png
    - title: Datasets View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/datasets.png
    - title: Grid View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/grid.png
    - title: Graph View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/graph.png
    - title: Calendar View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/calendar.png
    - title: Variable View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/variable_hidden.png
    - title: Gantt Chart
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/gantt.png
    - title: Task Duration
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/duration.png
    - title: Code View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.2/_images/code.png
apiVersion: v2
appVersion: 2.8.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.24
description: The official Helm chart to deploy Apache Airflow, a platform to programmatically
  author, schedule, and monitor workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/images/airflow_dark_bg.png
keywords:
- apache
- airflow
- workflow
- scheduler
maintainers:
- email: dev@airflow.apache.org
  name: Apache Airflow PMC
name: airflow
sources:
- https://github.com/apache/airflow
type: application
version: 1.13.0
